name: Build and deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-push:
    name: Build and Push 
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 8.3
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}

      - name: Setting image tag based on SHA
        run: |
          echo "IMAGE_TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
          # echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          
      - uses: satackey/action-docker-layer-caching@v0.0.11
        # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true     
        
      - name: Build Docker Image
        # if: ${{ false }}
        run: |
          sed -i 's/FROM php:php-var-cli-alpine/FROM php:${{ env.PHP_VERSION }}-alpine/g' Dockerfile
          make docker-build version=$IMAGE_TAG phpversion=${{ env.PHP_VERSION }}

      - name: Push Docker Image to docker hub
        # if: ${{ false }}
        run: |-
          make docker-push version=$IMAGE_TAG phpversion=${{ env.PHP_VERSION }}
